import math
from typing import List, Tuple

Vertex = Tuple[int, int, int]
Face = List[int]

def generate_regular_prism_int(n: int,
                               height: int = 1,
                               radius: int = 1,
                               center: Vertex = (0, 0, 0)) -> Tuple[List[Vertex], List[Face]]:
    """
    Génère un prisme régulier à base n-gon (n >= 3),
    avec sommets à coordonnées entières et triangulation complète.

    Arguments :
      n (int): nombre de côtés du polygone (>= 3)
      height (int): hauteur du prisme (entier)
      radius (int): rayon du polygone (entier)
      center (tuple): centre du prisme (x, y, z) (entiers)

    Retour :
      (vertices, faces)
        vertices : liste de tuples (x, y, z)
        faces : liste de triangles [i1, i2, i3]
    """
    if n < 3:
        raise ValueError("n must be >= 3")

    cx, cy, cz = center
    h2 = height / 2.0

    vertices: List[Vertex] = []

    # Génération des sommets (base inférieure puis supérieure)
    for z in (-h2, +h2):
        for i in range(n):
            theta = 2.0 * math.pi * i / n
            x = cx + radius * math.cos(theta)
            y = cy + radius * math.sin(theta)
            vertices.append((int(round(x)), int(round(y)), int(round(cz + z))))

    faces: List[Face] = []

    # --- Faces latérales triangulées ---
    for i in range(n):
        i0 = i
        i1 = (i + 1) % n
        i2 = n + (i + 1) % n
        i3 = n + i

        # Deux triangles par face latérale
        faces.append([i0, i1, i2])
        faces.append([i0, i2, i3])

    # --- Base supérieure ---
    top_face = [n + i for i in range(n)]
    t0 = top_face[0]
    for k in range(1, n - 1):
        faces.append([t0, top_face[k], top_face[k + 1]])

    # --- Base inférieure ---
    bottom_face = [i for i in range(n - 1, -1, -1)]
    b0 = bottom_face[0]
    for k in range(1, n - 1):
        faces.append([b0, bottom_face[k], bottom_face[k + 1]])

    return vertices, faces

def write_obj_file(filename: str, vertices: List[Vertex], faces: List[Face]) -> None:
    """
    Écrit les sommets et faces dans un fichier .obj.
    """
    with open(filename, 'w') as f:
        f.write("# Prism mesh generated by ChatGPT\n")
        for v in vertices:
            f.write(f"v {v[0]} {v[1]} {v[2]}\n")
        for face in faces:
            # +1 car les indices .obj commencent à 1
            f.write(f"f {' '.join(str(i + 1) for i in face)}\n")
    print(f"Mesh saved to {filename}")


if __name__ == "__main__":
    verts, faces = generate_regular_prism_int(n=6, height=6, radius=10)
    write_obj_file("prisme.obj", verts, faces)
